version: '3.1'

services:
  clean_db:
    image: mysql:5.7
    volumes:
      /mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    ports:
      - "3312:3306"
    environment:
      MYSQL_DATABASE: clean_db
      MYSQL_ROOT_USER: root
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
    